name: Long Usage

on: push

jobs:

  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
            submodules: recursive 
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --from markdown
            --output=BancroftRobodogsNotebook.pdf
            README.md
      - run: ls -al .
