name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt install pandoc texlive-latex-extra
      - run: echo $PWD
      - run: ls -al ./
      - run: ls -al ../
      - run: pandoc --from markdown --output=BancroftRobodogsNotebook.pdf README.md
      - run: ls -al .
